# Generated by Django 4.0.5 on 2022-07-18 22:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('library_books', '0001_initial'),
        ('customuser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpayment',
            name='payee_book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_books.book'),
        ),
        migrations.AddField(
            model_name='userpayment',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
