# Generated by Django 4.0.5 on 2022-07-06 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('book_code', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=200)),
                ('subject_area', models.CharField(max_length=200)),
                ('publication_date', models.DateField()),
                ('status', models.CharField(default='Available', max_length=50)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('borrower_id', models.BigIntegerField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
